public enum ENUM_DIFFICULTY_TYPE
{
	DIFFICULTY_LEVEL1 = 0,
	DIFFICULTY_LEVEL2 = 1,
	DIFFICULTY_LEVEL3 = 2,
	DIFFICULTY_LEVEL4 = 3,
	DIFFICULTY_LEVEL5 = 4,
	DIFFICULTY_LEVEL6 = 5,
	DIFFICULTY_LEVEL7 = 6,
	DIFFICULTY_LEVEL8 = 7,
	MAX_DIFFICULTY_TYPE = 8
}
