public enum ENUM_ENEMY_STATUS
{
	ENEMY_ATTACK = 0,
	ENEMY_DAMAGE = 1,
	ENEMY_RUN = 2,
	ENEMY_DEATH = 3,
	ENEMY_IDLE = 4,
	MAX_ENEMY_STATUS = 5,
	ENEMY_SUBSIDENCE = 6,
	ENEMY_DESTROY = 7,
	ENEMY_KNOCK = 8,
	ENEMY_SCREEN_GLIDING = 9
}
