public enum ENUM_ITEM_TYPE
{
	ITEM_NONE = 0,
	ITEM_GOLD = 1,
	ITEM_GOLD_POWER = 2,
	ITEM_SHOCK_WAVE = 3,
	ITEM_SHIELD = 4,
	ITEM_RESURRECTION = 5,
	ITEM_START_FROM_KM = 6,
	ITEM_GHOST = 7,
	ITEM_ENERGY = 8,
	ITEM_MAGNET = 9,
	ITEM_EXCHANGE = 10,
	ITEM_TREASUREBOX = 11,
	MAX_ITEM = 12
}
