public enum ENUM_CHARA_BUFFER
{
	BUFFER_NONE = 0,
	BUFFER_SPEED = 1,
	BUFFER_SHIELD = 2,
	BUFFER_MAGENT = 3,
	BUFFER_INVINCIBILITY = 4,
	BUFFER_LIGHT_WAY = 5,
	BUFFER_TRANSPARENT = 6,
	BUFFER_SHOCK_WAVE = 7,
	BUFFER_WORMHOLE = 8,
	BUFFER_EXCHANGE = 9,
	BUFFER_MAX = 10
}
